name: 'Release changelog'
description: 'Release new version or read version changelog'
author: 'superface.ai'
inputs:
  path-to-changelog:
    description: 'Path to changelog file in keep-a-changelog format'
    default: ./CHANGELOG.md
  version:
    description: 'Version to be released or read'
    required: true
  operation:
    description: 'release | read'
    required: true
outputs:
  changelog:
    description: 'Read or released changelog'
runs:
  using: 'node16'
  main: 'dist/index.js'
